### Criar Aluno 1
POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nomeCompleto": "Aluno 1",
    "email": "aluno@teste.com",
    "nomeCurso": "Matematica"
}

###
#Buscar
GET http://localhost:3000/alunos
Content-Type: application/json

###
# Atualizar
PUT http://localhost:3000/alunos/id
Content-Type: application/json

{
    "nomeCompleto": "Aluno Atualizado",
    "email": "aluno_atualizado@teste.com",
    "nomeCurso": "Engenharia"
}

### Remover Aluno 1
# No lugar de '/id' coloque o id do aluno a deletar
DELETE http://localhost:3000/alunos/id