### Criar Aluno 1
POST http://localhost:3000/alunos
Content-Type: application/json

{
    "nomeCompleto": "Aluno 4",
    "email": "aluno4@teste.com",
    "nomeCurso": "Geografia"
}

###
#Buscar
GET http://localhost:3000/alunos
Content-Type: application/json

###
# Atualizar
# No lugar de '/id' coloque o id do aluno para atualizar
PUT http://localhost:3000/alunos/id
Content-Type: application/json

{
    "nomeCompleto": "Aluno Atualizado",
    "email": "aluno_atualizado@teste.com",
    "nomeCurso": "Engenharia"
}

### Remover Aluno 1
# No lugar de '/id' coloque o id do aluno a deletar
DELETE http://localhost:3000/alunos/id